### ISSUE TITLE
jspm install doesn't seem to work

### ISSUE THREAD

**Issue by RobertTheGrey** [Mitranim/stylific#1]
Hi there - great lib!

I've tried `jspm install github:mitranim/stylific` and `jspm install npm:stylific` and they both download and make appropriate changes to `package.json` and `config.js`, but when I include and `import` like this:

`@import stylific from 'stylific'`

then I get the following console error:

`http://localhost:42852/jspm_packages/npm/stylific@0.8.5.js` returns a 404. Looking at the folders I can see `/lib/stylific.js` - so what am I doing wrong?

**Comment by RobertTheGrey** [comment]
I should mention that I can get this working if I tweak a few things to point at the lib folder, but I'm wondering why it doesn't work out the box?

**Comment by RobertTheGrey** [comment]
FYI - I've added this to JSPM project: https://github.com/jspm/registry/pull/526 because it looks like it's caused by main being an array instead of a string: https://github.com/Mitranim/stylific/blob/master/package.json#L17-L20

**Comment by mitranim** [comment]
Thanks for tracking this down! I was unaware of the issue because I always configured import paths manually. I suppose there's no harm in patching this. Just pushed a change to only list `.js` in `main`.
